# Generated by Django 3.2 on 2023-04-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='slud',
            new_name='slug',
        ),
    ]
